### ISSUE TITLE
Footnote backrefs

### ISSUE THREAD

**Issue by bjhess** [buttondown/tiptap-footnotes#15]
In Buttondown I see a footnote resolved with a backref link. See here:

![CleanShot 2024-12-18 at 10 57 15@2x](https://github.com/user-attachments/assets/54192e1c-da61-490f-ae8e-f0c2fe624477)

In my usage the footnote doesn't render with a backref. I end up with something like:

```html
<li id="fn:1" data-id="0e1717e6-e02b-4303-b9cd-222f722be1f8">
  <p>Footnotes</p>
</li>
```

Without the backref link that I see on Buttondown:

```html
<a class="footnote-backref" href="#fnref:1">↩</a>
```

I don't find any instances of `backref` in the repo, so I'm wondering if you're extending the extension in Buttondown to achieve this?

**Comment by jmduke** [comment]
Yup; that's being added what we're actually using on the backend to _render_ the final HTML spat out by Tiptap (since we need to be able to render tiptap and 'plain' Markdown to the same final artifact), which is the

**Comment by jmduke** [comment]
In terms of extending the extension to achieve this — I am not sure we want to be so heavily prescriptive as to _default_ to adding the backref, but I think we could absolutely expose a hook to allow overriding the render (which would also solve #11).

**Comment by bjhess** [comment]
That makes sense, @jmduke. Thanks for sharing what y'all are doing. Just added render-time backref processing to Pika. Thanks!

(I'm assuming this issue can be closed, but I'll leave that up to you!)
