### ISSUE TITLE
The demo does not work.

### ISSUE THREAD

**Issue by andyj2022** [buttondown/tiptap-footnotes#8]
https://codesandbox.io/p/devbox/tiptap-footnotes-example-7n53s4

There are 2 'setup failed' erros. Tested: Firefox and Chrome (Windows 11).

**Comment by jmduke** [comment]
@mary-ext Mind poking at this? I think we might need to just rebuild the Sandbox since it's under @tk04's name.

**Comment by mary-ext** [comment]
I think we can definitely have the actual example hosted on this source code and have StackBlitz point to this repository for it. e.g, [Next.js hello world example](https://stackblitz.com/github/vercel/next.js/tree/canary/examples/hello-world?file=package.json)

**Comment by mary-ext** [comment]
Fixed. https://github.com/buttondown/tiptap-footnotes/commit/74d3467974e9d72da4fabeb35042fab0611c14ba

**Comment by andyj2022** [comment]
Sorry. The [new demo](https://stackblitz.com/github/buttondown/tiptap-footnotes/tree/demo/examples/react?file=src%2FApp.tsx&title=tiptap-footnotes%20demo) also fails (Firefox and Chrome):



![imagen](https://github.com/user-attachments/assets/d1097d1f-1505-4cd9-bf85-6de46195e828)

**Comment by mary-ext** [comment]
Ahh, could you see if changing `demo` to `main` would work? I've linked to the wrong branch it seems

**Comment by andyj2022** [comment]
Yes. Thanks!

https://stackblitz.com/github/buttondown/tiptap-footnotes/tree/main/examples/react?file=src%2FApp.tsx&title=tiptap-footnotes%20demo
