### ISSUE TITLE
Enable ability to wrap Blockquote in footnote using options/`.configure()`

### ISSUE THREAD

**Issue by StephanMeijer** [buttondown/tiptap-footnotes#9]
In many document standards, such as OOXML/`.docx`, it is possible to place elements like lists, Blockquotes, images, tables, etc. in a Footnote.

I would like to see the possibility to be able to configure that in this extension, without the need to extend it.

https://github.com/buttondown/tiptap-footnotes/blob/main/package/src/footnotes/footnote.ts#L18

**Comment by jmduke** [comment]
@mary-ext want to tackle this when you get some free time?
